version: '3'
services:
  mysql:
    image: "mysql/mysql-server:latest"
    command: '--default-authentication-plugin=mysql_native_password'
    expose:
      - "3306"
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - test_net
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    networks:
      - test_net
    environment:
      DB_HOST: mysql
networks:
  test_net:
    driver: bridge